### ISSUE TITLE
`Fluid.waveform` incorrectly displaying first sample

### ISSUE THREAD

**Issue by MattS6464** [flucoma/fluid.waveform#26]
`fluid.waveform` appears to add an extra sample at the start and cuts off the last sample. This happens on both the audiobuffer layer and the featuresbuffer layer.
<img width="671" alt="fluid waveform bug" src="https://github.com/flucoma/fluid.waveform/assets/141223694/80ebbb83-ceb4-4630-9ebb-8f3ddd3ce661">

**Comment by tremblap** [comment]
Sharing the code to reproduce would be great next time @MattS6464 :) especially since it is sooooo clean, I love your Max style.

Here it is recoded and dirty and without comments
<pre><code>
----------begin_max5_patcher----------
658.3ocwWssaiBCD8Y3qvhmyFg4VH6S8+X0pHCXx5HtIaSZppZ+1W6wPZZSB
wMkc6CfiMCb3blyL37rqiWV6ApvC8SzuPNNO653.KoWvYXtiWM4PdEQ.g4US
EBxVp2By0jzCRX87JJgu.QJJpHOQ4nRJQ1yohr9xR0TIUHQbZw380otDsQRj
r1lMUrFZdaeC7jBFhnoutsWVQk.t3gUYE.ZsY69ANX7gYhS9TG0vDOOzuGwg
Hy+CqY6FNMWZtZDd8R+EnnDXHveELDrz+3Mofl0LhbfdsWbc0mVXoHsSzy7r
lGgGEEBmTSkT9FZCIqBXi+s4XIqREeMbAuxpdVwxGI6oks75W8tsNrNTODGA
yB0CWVHv2gPXqagzWvZOwpXu3g+RlfzX8Y7pfuYOP52pE.6u9emE3r2i2KFI
mKFqtZJsrpkn7FS9iJl.FmL8uFCVeLX8ChSzCIQmPaiW7nj9AO4aJR7cnHMz
GUz7rZBCjuZZU9ffT2IPwWVzBNWzRtsnkQZ1NopfwPuvPsRnbEg9SWUfmOtK
QYnLq4Z7U4JPQqnZrojeMP0vf+aL0TbpMoApDN5gBU1l0.eG7y04K55h.Xjl
l9AFFGAoXbR57y+q052G4uLPcDoNRslsg2Wad7PCNy25WEO+s4uRZVUyUXLi
19gro8zSRReSVzGnW7mHWBQ3o290G1CHfhd82ybQaOOe78ZnRD8FNm3kOIF8
9zzAcQw0VfFeHSiT3bfD1BjRmAfzZG9VLBOC.EYAghmAbBs.mn4HCYANm6DL
dcRW2dJWLDL.gpddWKWOMcALk0XlFCS4z8rw3MqP3pJPop7S8+af52CIllwd
0sEpMMn12moNSQNEjPuB8NIDcDCOfVJtu39WFv6LZ.
-----------end_max5_patcher-----------
</code></pre>

**Comment by tremblap** [comment]
investigation results:

1. adding at line 666 of waveform.js `ld.data.forEach(function(s){post(s.data + '\n');});` shows that the array passed to fav is the right one...

2. pinging around line 767 of the generated fav-max.js, which is line 239 of the src/display-jsui.js, I can see that the error is in the resampling. desc[0] and desc[1] are right when printed, but the resampling is not right.

I now need to learn how to find out which definition of the `sample` method is used as I cannot find it anywhere to fix it...

**Comment by tremblap** [comment]
using this streamlined patch where the waveform object has 20 pixel wide for a 5 sample-long buffer makes the resampling data obvious. Printing `desc[1]` and its resampling `max` is good to understand the issue.

**Comment by tremblap** [comment]
found it. a fav.js issue. PR made there and here.
